/* Generated by AN DISI Unibo */ 
package it.unibo.ctxsonar
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "172.16.0.2", this, "carparking.pl", "sysRules.pl"
	)
}

