/* Generated by AN DISI Unibo */ 
package it.unibo.sonaractor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonaractor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "polling"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val mock = carparking.presence.PresenceSonar(carparking.presence.MockSonar())
				var previous = mock.isPresent()
				var present = previous
		return { //this:ActionBasciFsm
				state("polling") { //this:State
					action { //it:State
						 present = mock.isPresent()  
						if(  present && previous!=present  
						 ){emit("outdoorOccupied", "outdoorOccupied(0)" ) 
						}
						if(  !present && previous!=present  
						 ){emit("outdoorCleared", "outdoorCleared(0)" ) 
						}
						 previous = present  
						delay(500) 
					}
					 transition( edgeName="goto",targetState="polling", cond=doswitch() )
				}	 
			}
		}
}
