/* Generated by AN DISI Unibo */ 
package it.unibo.parkmanagerserviceactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkmanagerserviceactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "moveToHome"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				var Slotnum = 1
				var Tokenid = 1
		return { //this:ActionBasciFsm
				state("moveToHome") { //this:State
					action { //it:State
						forward("goto", "goto(home)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t0",targetState="acceptIN",cond=whenDispatch("enterRequest"))
					transition(edgeName="t1",targetState="acceptOUT",cond=whenDispatch("exitRequest"))
				}	 
				state("acceptIN") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="informIN", cond=doswitch() )
				}	 
				state("informIN") { //this:State
					action { //it:State
						forward("slotnum", "slotnum($Slotnum)" ,"parkserviceguiactor" ) 
					}
					 transition( edgeName="goto",targetState="do_informIN", cond=doswitchGuarded({ Slotnum > 0  
					}) )
					transition( edgeName="goto",targetState="moveToHome", cond=doswitchGuarded({! ( Slotnum > 0  
					) }) )
				}	 
				state("do_informIN") { //this:State
					action { //it:State
					}
					 transition(edgeName="t2",targetState="moveToIn",cond=whenDispatch("carEnter"))
				}	 
				state("moveToIn") { //this:State
					action { //it:State
						forward("notice", "notice(carEnter(received))" ,"parkserviceguiactor" ) 
						forward("goto", "goto(indoor)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t3",targetState="receipt",cond=whenDispatch("movementDone"))
				}	 
				state("receipt") { //this:State
					action { //it:State
						forward("tokenid", "tokenid($Slotnum)" ,"parkserviceguiactor" ) 
					}
					 transition( edgeName="goto",targetState="moveToSlotIn", cond=doswitch() )
				}	 
				state("moveToSlotIn") { //this:State
					action { //it:State
						 Slotnum = 0  
						forward("goto", "goto(parking)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t4",targetState="moveToHome",cond=whenDispatch("movementDone"))
				}	 
				state("acceptOUT") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("exitRequest(TOKENID)"), Term.createTerm("exitRequest(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Tokenid = payloadArg(0).toInt()  
						}
						forward("notice", "notice(exitRequest(received))" ,"parkserviceguiactor" ) 
					}
					 transition( edgeName="goto",targetState="findSlot", cond=doswitchGuarded({ Slotnum == 0  
					}) )
					transition( edgeName="goto",targetState="moveToHome", cond=doswitchGuarded({! ( Slotnum == 0  
					) }) )
				}	 
				state("findSlot") { //this:State
					action { //it:State
						 Slotnum = 1  
					}
					 transition( edgeName="goto",targetState="moveToSlotOut", cond=doswitch() )
				}	 
				state("moveToSlotOut") { //this:State
					action { //it:State
						forward("goto", "goto(parking)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t5",targetState="moveToOut",cond=whenDispatch("movementDone"))
				}	 
				state("moveToOut") { //this:State
					action { //it:State
						forward("goto", "goto(outdoor)" ,"trolleyactor" ) 
					}
					 transition(edgeName="t6",targetState="moveToHome",cond=whenDispatch("movementDone"))
				}	 
			}
		}
}
